version: '2'
services: 
  wiremock:
    image: wiremock
    ports:
      - "7070:7070"

  dropwizard:
    image: dropwizard-app
    ports:
      - "9080:9080"
      - "9090:9090"
    links:
      - wiremock
